# minibatch related
batch-size: 8
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced
# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 1000
patience: 5

# scheduled sampling option
sampling-probability: 0.0

# encoder related
etype: blstmp     # encoder architecture type
elayers: 4
eunits: 1280
eprojs: 1280
subsample: "1_2_2_2_1" # skip every n frame from input to nth layers
encoder-dropout: .1

# decoder related
dlayers: 2
dunits: 1800
decoder-dropout: 0.0

# attention related
atype: location
adim: 1280
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.05
