# This configuration requires 4 gpus with 12GB memory
#accum-grad: 4
accum-grad: 8
#accum-grad: 10
adim: 256
aheads: 4
backend: pytorch
#batch-bins: 15000000
batch-bins: 2000000
batch-count: bin
dlayers: 6
dropout-rate: 0.1
dunits: 2048
elayers: 12
epochs: 120
eunits: 2048
grad-clip: 5
lsm-weight: 0.1
model-module: espnet.nets.pytorch_backend.e2e_asr_transformer:E2E
mtlalpha: 0.3
opt: noam
patience: 0
sortagrad: 0
transformer-attn-dropout-rate: 0.0
transformer-init: pytorch
transformer-input-layer: conv2d
transformer-length-normalized-loss: false
transformer-lr: 10.0
transformer-warmup-steps: 25000