# network architecture
# encoder related
encoder: transformer
encoder_conf:
    input_layer: "linear"
    num_blocks: 3
    linear_units: 512
    dropout_rate: 0.1
    output_size: 256  # dimension of attention
    attention_heads: 4
    attention_dropout_rate: 0.0

# decoder related
decoder: linear

# minibatch related
batch_type: folded
batch_size: 32

# optimization related
optim: adam
accum_grad: 2
grad_clip: 5
patience: 0
max_epoch: 100
optim_conf:
    lr: 1.0
scheduler: noamlr
scheduler_conf:
    warmup_steps: 25000

# others:
best_model_criterion:
-  - valid
   - acc
   - max
keep_nbest_models: 10

init: chainer
